description: 

baseurl: "" # the subpath of your site, e.g. /blog
url: http://ryankwon.github.io # the base hostname & protocol for your site
disqus_shortname : dataspheres

# Build settings
markdown: redcarpet
highlighter: pygments

permalink: :title.html


gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

exclude: ['node_modules', 'package.json', 'gulpfile.js']


